### ISSUE TITLE
Can't run/build/install on macOS Mojave (10.14.1)

### ISSUE THREAD

**Issue by Danl2620** [paulhammond/jp#2]
I encounter issues installing, building, or running prebuilt binaries of `jp` on macOS Mojave. I can post the errors messages if you like.

**Comment by paulhammond** [comment]
Hi, thanks for the report and sorry to take so long to respond. The problem was in go itself, the old binaries were built with a very old version of go that had some incompatibilities with new versions of macOS.

I've just released a new version of jp, and with it some new prebuilt binaries built with go 1.3. They should now work on recent versions of macOS. If I'm wrong please reopen this issue with some details!
